version: '3'

services:
  nextjs-app:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: runner
    image: nextjs-app
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3001:3000'

  nextjs-docs:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: docs
    image: nextjs-docs
    volumes:
      - ../../:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '6001:6006'
