version: '3'

services:
  app:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: runner
    image: app
    ports:
      - '3001:3000'

  docs:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
      target: docs
    image: docs
    ports:
      - '6006:6006'
